.TH tcos-devices 1 "Mar 11, 2007" "tcos-devices man page"

.SH NAME
tcos-devices \- Python GTK2 gui and daemon that allow to access thin client filesystems and devices easy.

.SH DESCRIPTION

.PP
\fBtcos-devices\fP is a python GUI and daemon exec in client session startup and allows to:
 * Mount / umount floppy cdrom (in gui mode)
 * Detect USB devices and mount automatically (in daemon mode)

tcos-devices use xauth with tcosxmlrpc (MIT-MAGIC-COOKIE)

.SH OPTIONS
.B [no options]
 With no options will launch GUI in normal mode.

.B --daemon
 Launch in daemon mode and connect to thin client UDEV to detect BLOCK events

.B --hidden
 Start GUI in systray, but hidden.

.B --host=xx.xx.xx.xx
 Overwrite DISPLAY with this var (not work unless thin client Xorg is started with -ac)

.B --debug
 Show verbose output when running

.B --help
 Some usage help about tcos-devices


.SH BUGS
Contact Mario Izquierdo <mariodebian@gmail.com>

Info about TCOS project: http://soleup.eup.uva.es/mediawiki/index.php/TCOS

.SH SEE ALSO
tcos-devices(1)

.SH AUTHOR
Mario Izquierdo (mariodebian) <mariodebian@gmail.com>
