debian/tmp/etc/tcos/tcosmonitor.conf
debian/tmp/etc/tcos/tcos-devices-ng.conf

debian/tmp/usr/share/tcosmonitor/images/*

debian/tmp/usr/share/tcosmonitor/tcos-volume-manager.glade
debian/tmp/usr/share/tcosmonitor/tcosmonitor.glade
debian/tmp/usr/share/tcosmonitor/tcospersonalize.glade
debian/tmp/usr/share/tcosmonitor/tray.glade

debian/tmp/usr/share/applications/tcosmonitor.desktop
debian/tmp/usr/share/applications/tcospersonalize.desktop

debian/tmp/usr/bin/tcosmonitor.py
debian/tmp/usr/bin/tcospersonalize.py
debian/tmp/usr/bin/tcos-volume-manager.py
debian/tmp/usr/bin/tcos-devices-ng.py
debian/tmp/usr/bin/tcos-server-utils.py    usr/sbin/

debian/tmp/usr/lib/python*/site-packages/tcosmonitor/htmltextview.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/Initialize.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosActions.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosClassView.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosExtensions.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosIconView.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosListView.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosMenus.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosPreferences.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosStaticHosts.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosTrayIcon.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosTrayIcon2.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/TcosXmlRpc.py
debian/tmp/usr/lib/python*/site-packages/tcosmonitor/WakeOnLan.py

debian/tmp/usr/lib/python*/site-packages/tcosmonitor/extensions/*.py


debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/htmltextview.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/Initialize.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosActions.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosClassView.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosExtensions.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosIconView.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosListView.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosMenus.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosPreferences.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosStaticHosts.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosTrayIcon.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosTrayIcon2.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/TcosXmlRpc.py
debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/WakeOnLan.py

debian/tmp/usr/lib/python*/dist-packages/tcosmonitor/extensions/*.py
