#!/bin/bash


# remove obsolete files
if [ -f /etc/xdg/autostart/tcos-devices.desktop ]; then
  rm -f /etc/xdg/autostart/tcos-devices.desktop
fi

if [ -f /etc/X11/Xsession.d/81tcos-dbus-client ]; then
  rm -f /etc/X11/Xsession.d/81tcos-dbus-client
fi

if [ -f /etc/xdg/autostart/tcos-devices-daemon.desktop ]; then
  rm -f /etc/xdg/autostart/tcos-devices-daemon.desktop
fi

if [ -f /etc/xdg/autostart/tcos-volume-manager.desktop ]; then
  rm -f /etc/xdg/autostart/tcos-volume-manager.desktop
fi

if [ -f /etc/xdg/autostart/tcos-devices-autostart.desktop ]; then
  rm -f /etc/xdg/autostart/tcos-devices-autostart.desktop
fi



#DEBHELPER#
