debian/tmp/etc/tcos/tcosmonitor.conf
debian/tmp/etc/tcos/tcos-devices-ng.conf

debian/tmp/usr/share/tcosmonitor/images/*

#debian/tmp/usr/share/tcosmonitor/tcos-volume-manager.glade
#debian/tmp/usr/share/tcosmonitor/tcosmonitor.glade
#debian/tmp/usr/share/tcosmonitor/tcospersonalize.glade
#debian/tmp/usr/share/tcosmonitor/tray.glade
debian/tmp/usr/share/tcosmonitor/ui/*

debian/tmp/usr/share/applications/tcosmonitor.desktop
debian/tmp/usr/share/applications/tcospersonalize.desktop

debian/tmp/usr/bin/tcosmonitor
debian/tmp/usr/bin/tcospersonalize
debian/tmp/usr/bin/tcos-volume-manager
debian/tmp/usr/bin/tcos-devices-ng
debian/tmp/usr/bin/tcos-server-utils    usr/sbin/

debian/tmp/usr/lib/python*/*/tcosmonitor/htmltextview.py
debian/tmp/usr/lib/python*/*/tcosmonitor/Initialize.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosActions.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosClassView.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosExtensions.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosIconView.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosListView.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosMenus.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosPreferences.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosStaticHosts.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosTrayIcon.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosTrayIcon2.py
debian/tmp/usr/lib/python*/*/tcosmonitor/TcosXmlRpc.py
debian/tmp/usr/lib/python*/*/tcosmonitor/WakeOnLan.py

debian/tmp/usr/lib/python*/*/tcosmonitor/extensions/*.py
