#!/bin/bash


# remove obsolete files
OLD_FILES="
 /etc/tcos/hooks-addons/tcosmonitor \
 /etc/tcos/hooks-addons/tcoshttpd \
 /etc/xdg/autostart/tcos-devices.desktop \
 /etc/X11/Xsession.d/81tcos-dbus-client \
 /etc/xdg/autostart/tcos-devices-daemon.desktop \
 /etc/xdg/autostart/tcos-volume-manager.desktop \ 
 /etc/xdg/autostart/tcos-devices-autostart.desktop \
"

for _file in ${OLD_FILES}; do
  if [ -f ${_file} ] ; then
    echo "  tcosmonitor: Deleting deprecated ${_file}"
    rm -f ${_file}
  fi
done



#DEBHELPER#
