usr/sbin/tcospasswd
usr/sbin/update-tcospasswd
usr/lib/tcos/tcos-udevd.sh
usr/lib/tcos/tcosxmlrpc
usr/lib/tcos/lockscreen
usr/lib/tcos/screenshot.sh
usr/lib/tcos/soundctl.sh
usr/lib/tcos/starthttpd.sh
usr/lib/tcos/getinfo.sh
usr/lib/tcos/useallmodules.sh
usr/lib/tcos/devicesctl.sh
usr/share/initramfs-tools-tcos/hooks-addons/tcosmonitor
usr/share/tcosmonitor/xmlrpc/httpd2.conf
usr/share/tcosmonitor/xmlrpc/mime.types
usr/share/tcosmonitor/xmlrpc/abyss.conf
usr/share/tcosmonitor/xmlrpc/050_tcos_devices.rules
usr/share/tcosmonitor/xmlrpc/locked.png

